/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IBgGradient: typeof import('~icons/bg/gradient')['default']
    ICustomMail: typeof import('~icons/custom/mail')['default']
    ICustomMenu: typeof import('~icons/custom/menu')['default']
    IIconPath: typeof import('~icons/ic/on-path')['default']
    IToolsFigma: typeof import('~icons/tools/figma')['default']
    IToolsPhotoshop: typeof import('~icons/tools/photoshop')['default']
    IToolsVue: typeof import('~icons/tools/vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
