/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IBackgroundGradient: typeof import('~icons/background/gradient')['default']
    IBgGradient: typeof import('~icons/bg/gradient')['default']
    ICustomMail: typeof import('~icons/custom/mail')['default']
    ICustomMenu: typeof import('~icons/custom/menu')['default']
    IToolsDavinci: typeof import('~icons/tools/davinci')['default']
    IToolsPhotoshop: typeof import('~icons/tools/photoshop')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
